---
title: "Teaching: Datasets for classes"
---
<link rel="stylesheet" href="styles.css" type="text/css">


## Data for courses

* Forest Fire data
    + http://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv
    + http://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.names
    + http://www.dsi.uminho.pt/~pcortez/fires.pdf
* Baseball Hitting Statistics
    + http://www.seanlahman.com/baseball-archive/statistics/
    + <a href="data/Lahman_Batting2018.csv">Lahman_Batting2018.csv</a>
    + <a href="data/Lahman_Batting2021.csv">Lahman_Batting2021.csv</a>
    + <a href="data/Lahman_People2021.csv">Lahman_People2021.csv</a>
* Yearly Mean Sunspots
    + http://www.sidc.be/silso/infosnytot
    + <a href="data/sunspots_yearly.csv">sunspots_yearly.csv</a>
* Ohio Behavioral Risk Factor Surveillance System
    + https://www.cdc.gov/brfss/annual_data/annual_2018.html
    + https://www.cdc.gov/brfss/annual_data/2018/pdf/codebook18_llcp-v2-508.pdf
    + <a href="data/ohioBRFSS2018.csv">ohioBRFSS2018.csv</a>
* Census Bureau - Retail Trade and Food Services
    + https://www.census.gov/econ/currentdata/dbsearch?program=MRTS&startYear=1992&endYear=2019&categories=44X72&dataType=SM&geoLevel=US&adjusted=1&notAdjusted=1&submit=GET+DATA&releaseScheduleId=
    + <a href="data/monthlyRetailNSA.xls">monthlyRetailNSA.xls</a>
    + <a href="data/monthlyRetailNSA.csv">monthlyRetailNSA.csv</a>
* Weekly US Unemployment Insurance Claims (funky format)
    + <a href="data/usUnemploymentClaims.csv">usUnemploymentClaims.csv</a>
* Opioid deaths from CDC and related
    + <a href="data/stateOpioidDeaths2012.csv">stateOpioidDeaths2012.csv</a>
    + <a href="data/stateOpioidDeaths2017.csv">stateOpioidDeaths2017.csv</a>
    + <a href="data/state_Opioid_Deaths2019.csv">state_Opioid_Deaths2019.csv</a>
    + <a href="data/state_abb_codes.csv">state_abb_codes.csv</a>
    + <a href="data/censusRegions.csv">censusRegions.csv</a>
    + <a href="data/marchStateUnemployment.csv">marchStateUnemployment.csv</a>
    + <a href="data/gasoline_prices.csv">gasoline_prices.csv</a>
* Cincinnati Weather Forecast
    + <a href="https://community.amstat.org/stat-computing/data-expo/data-expo-2018">Data Expo 2018</a>
    + <a href="data/cincy2016forecast.txt">cincy2016forecast.txt</a>
* Facebook Metrics
    + <a href="data/dataset_Facebook.csv">dataset_Facebook.csv</a>
    + <a href="data/Facebook_metrics.txt">Facebook_metrics.txt</a>
    + https://archive.ics.uci.edu/ml/datasets/Facebook+metrics
* Gapminder Data
    + Income, life expectancy, happiness, human development index, population, and mapping of countries to regions. Most recent observed data is 2018, hence the file name.
    + <a href="data/gapminder2018.RData">gapminder2018.RData</a>
    + https://www.gapminder.org/data/
* Ohio Population Estimates (2019)
    + Extracted from the American Community Survey
    + Population estimate for each county, stratified by age groups
    + <a href="data/OhioCountyPopulation_byAge2019.csv">OhioCountyPopulation_byAge2019.csv</a>
* Ohio Population from 2020 Census
    + Extracted from Original census <a href="https://www2.census.gov/programs-surveys/popest/datasets/2020-2021/counties/asrh/cc-est2021-agesex-39.csv">record (CSV)</a>.
    + Population estimate for each county, stratified by age groups
    + <a href="data/OhioCountyPopulation_byAge2020.csv">OhioCountyPopulation_byAge2020.csv</a>
* Popular baby names in the USA from 1880 to 2020.
    + <a href="data/usBabyNames1880_2020.csv">usBabyNames1880_2020.csv</a>
    + Obtained from Kaggle, originally from the US Social Security Administration
* Palmer penguins data for STA 308
    + Data munged from original Palmer penguins data for use in class
    + <a href="data/palmer_penguins.csv">palmer_penguins.csv</a>
    + <a href="data/penguins2007.csv">penguins2007.csv</a>
    + <a href="data/penguins2008.txt">penguins2008.txt</a>
    + <a href="data/penguins2009.RData">penguins2009.RData</a>
* University League Tables
    + Data from: "University league tables have no legs to stand on" by Adrian Barnett, Elizabeth Gadd
    + <a href="data/senior_expert_ratings_tall.csv">senior_expert_ratings_tall.csv</a> in a "tall" format
    + <a href="data/senior_expert_ratings_wide.csv">senior_expert_ratings_wide.csv</a> in a "wide" format
* Sports Viewership Data
    + <a href="data/viewership_data.csv">viewership_data.csv</a>
    + Data to mimic the first plot from fivethirtyeight: https://fivethirtyeight.com/features/how-massive-the-nfl-really-is-in-4-charts/
    + Data was obtained via wikipedia for the various sports
* Automobile Fuel Efficiency
    + <a href="data/auto-mpg-data-original.txt">auto-mpg-data-original.txt</a>
    + Originally from: https://archive.ics.uci.edu/dataset/9/auto+mpg
* Fabricated <i>toy</i> dataset of Bachelor of Arts - Data Analytics students
    + CSV Format: <a href="data/bada_students_csv.txt">bada_students_csv.txt</a>
    + Space Separated: <a href="data/bada_students_tab.txt">bada_students_tab.txt</a>
    + Fixed Width: <a href="data/bada_students_fwf.txt">bada_students_fwf.txt</a>
* Natality and Population in time
    + Data is from the US Census and CDC - by year and other demographic information
    + CDC Natality: <a href="data/natalityInTime0122.RData">natalityInTime0122.RData</a>
    + US Census Bureau Population Estimates: <a href="data/census_population_by_age_sex.csv">census_population_by_age_sex.csv</a>
* Stephen Curry game-level statistics in the playoffs
    + From Basketball reference
    + Data: <a href="data/stephCurryPlayoffs.csv">stephCurryPlayoffs.csv</a>
* CDC Flu & Pneumonia Mortality
    + 2018: <a href="data/fluPneumonia_2018.csv">fluPneumonia_2018.csv</a>
    + 2021: <a href="data/fluPneumonia_2021.csv">fluPneumonia_2021.csv</a>
    
## Data for STA 363 and 672

In Fall 2025, STA 363 underwent an overall, below are the datasets used for the daily lecture notes in that course.

* Data from Rossman/Chance Applet Collection
    + <a href="https://www.nature.com/articles/nn1200_1237">Sleep Deprivation Study</a>: <a href="data/rossman_sleep_deprivation.txt">rossman_sleep_deprivation.txt</a>
    + <a href="https://pubmed.ncbi.nlm.nih.gov/22451320/">Brain size by exercise</a>: <a href="data/rossman_brain_size.txt">rossman_brain_size.txt</a>
    + <a href="https://pubmed.ncbi.nlm.nih.gov/17341711/">Changes in BMI by Diet</a>: <a href="data/rossman_diet_study.csv">rossman_diet_study.csv</a>
* Ohio and Midwest Small College data
    + <a href="data/ohio_small_colleges.csv">ohio_small_colleges.csv</a>
    + <a href="data/midwest_small_colleges.csv">midwest_small_colleges.csv</a>
    + <a href="data/sta363_dataCode_smallCollegeData.R">sta363_dataCode_smallCollegeData.R</a>
    + Original source: <a href="https://www.collegeresults.org/">collegeresults.org</a>
* UV Light Penetration Depths and DOC Measures
    + <a href="data/berry_uv_doc.csv">berry_uv_doc.csv</a>
    + <a href="data/sta363_dataCode_berryUVdata.R">sta363_dataCode_berryUVdata.R</a>
    + Berry et al. (2026) <a href="https://doi.org/10.1139/cjfas-2024-0407">Decreased water transparency of nearshore Laurentian Great Lakes habitats is driven by increased dissolved organic carbon</a>. *Canadian Journal of Fisheries and Aquatic Sciences*. 83: 1-9.
* Dental Hardness (Two-way with block design)
    + <a href="data/dental_filling_hardness.csv">dental_filling_hardness.csv</a>
* Beverage Sales (Two-way design)
    + <a href="data/beverageSales.csv">beverageSales.csv</a>
* Dehumidifier Power usage (One-way with Block design)
    + <a href="data/humidity.txt">humidity.txt</a>
    

    



